import {Game,CHARACTERS,UPGRADES} from './engine.js';
import {drawWorld,drawPortrait} from './art.js';
const $=s=>document.querySelector(s), canvas=$('#world'),ctx=canvas.getContext('2d',{alpha:false});
const icons={fire:'✦',orbit:'☽',thunder:'ϟ',frost:'❄',atk:'⚔',speed:'»',magnet:'✧',hp:'♥',cooldown:'◴',heal:'♥'};
const timeText=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
let stored={};try{stored=JSON.parse(localStorage.getItem('lanternfall.v1')||'{}')||{}}catch{}
const nonnegative=value=>Number.isFinite(Number(value))?Math.max(0,Number(value)):0;
let settings={sound:stored.sound===true,reduced:typeof stored.reduced==='boolean'?stored.reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,best:nonnegative(stored.best),wins:Math.floor(nonnegative(stored.wins))};
const save=()=>{try{localStorage.setItem('lanternfall.v1',JSON.stringify(settings))}catch{}};
let selected='ember',game=null,screen='menu',prevState='',keys=new Set(),axis={x:0,y:0},dash=false,last=performance.now(),clock=0,hudClock=0,lastLevel=1,lastKills=0,lastHp=0,annTime=0,lastPhase='',audio;
let demo={worldSize:2400,time:0,player:{x:1200,y:1200,radius:12,hp:100,maxHp:100,character:'ember',color:'#efbb76'},enemies:[],bullets:[],enemyBullets:[],drops:[],effects:[],texts:[],weapons:{fire:1},evolved:{}};
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function sound(freq=500,len=.06,volume=.025){if(!settings.sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,audio.currentTime+len);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+len)}catch{}}
function settingsUI(){$('#sound').innerHTML=`♫ <span>音效${settings.sound?'開':'關'}</span>`;$('#sound').setAttribute('aria-label',settings.sound?'關閉音效':'開啟音效');$('#sound').setAttribute('aria-pressed',String(settings.sound));$('#motion').innerHTML=`◌ <span>${settings.reduced?'減少動態':'動態正常'}</span>`;$('#motion').setAttribute('aria-pressed',String(settings.reduced));$('#best').textContent=`最長守夜 ${timeText(settings.best)}`}
$('#sound').onclick=()=>{settings.sound=!settings.sound;save();settingsUI();sound()};$('#motion').onclick=()=>{settings.reduced=!settings.reduced;save();settingsUI()};settingsUI();
function renderCharacters(){const tags={ember:'均衡 / 焰矢',tide:'控場 / 霜環',thorn:'近戰 / 月刃'};$('#characters').replaceChildren();for(const c of CHARACTERS){const b=document.createElement('button');b.className='character'+(c.id===selected?' selected':'');b.setAttribute('aria-pressed',String(c.id===selected));b.innerHTML=`<canvas width="80" height="80" aria-hidden="true"></canvas><span><b>${c.name}</b><small>${c.description}</small></span><span class="tag">${tags[c.id]||c.title}</span>`;b.onclick=()=>{selected=c.id;renderCharacters();sound(650)};$('#characters').append(b);drawPortrait(b.querySelector('canvas'),c.id)}}renderCharacters();
function clearInput(){keys.clear();axis={x:0,y:0};dash=false;const captured=pointer;pointer=null;const joystick=$('#joystick');if(captured!==null&&joystick.hasPointerCapture?.(captured)){try{joystick.releasePointerCapture(captured)}catch{}}$('#stick').style.transform='none'}
function start(){clearInput();game=new Game({seed:Math.floor(Date.now()%2147483647),character:selected});game.start();screen='game';prevState='';lastPhase='';lastLevel=1;lastKills=0;lastHp=game.player.hp;$('#app').classList.add('playing');$('#menu').hidden=true;$('#hud').hidden=false;$('#pause').hidden=false;$('#loadout').hidden=false;$('#touch-controls').hidden=!(matchMedia('(pointer: coarse)').matches||innerWidth<700);$('#hero-name').textContent=CHARACTERS.find(c=>c.id===selected)?.name||'守夜人';$('#overlay').hidden=true;last=performance.now();announce('守住微光，直到黎明。');sound(440,.25);updateHUD();canvas.focus()}
function home(){clearInput();game=null;screen='menu';$('#app').classList.remove('playing');for(const s of ['#hud','#pause','#loadout','#touch-controls','#overlay'])$(s).hidden=true;$('#menu').hidden=false;$('#announcement').textContent='';settingsUI();$('#start').focus()}
$('#start').onclick=start;$('#pause').onclick=()=>{if(!game)return;clearInput();game.togglePause();syncState()};
function announce(text){$('#announcement').textContent=text;$('#announcement').style.opacity=1;annTime=3}
function updateHUD(){if(!game)return;const p=game.player;$('#health-fill').style.width=`${Math.max(0,p.hp/p.maxHp*100)}%`;$('#health-text').textContent=`♥ ${Math.ceil(p.hp)} / ${p.maxHp}`;$('#time').textContent=timeText(game.time);$('#kills').textContent=`${game.kills} 擊破`;$('#level').textContent=`Lv. ${game.level}`;$('#xp-text').textContent=`${Math.floor(game.xp)} / ${game.xpNeeded}`;$('#xp-fill').style.width=`${Math.min(100,game.xp/game.xpNeeded*100)}%`;let phase=game.time>=360?'終夜 · 長夜之王':game.time>=240?'第三夜 · 怪潮':game.time>=120?'第二夜 · 暗湧':'第一夜 · 甦醒';$('#phase').textContent=phase;if(lastPhase&&phase!==lastPhase)announce(phase);lastPhase=phase;const boss=game.enemies.find(e=>e.type==='boss');$('#boss-bar').hidden=!boss;if(boss)$('#boss-fill').style.width=`${100*boss.hp/boss.maxHp}%`;$('#loadout').innerHTML=Object.entries(game.weapons).filter(([,v])=>v>0).map(([k,v])=>`<div class="weapon-chip ${game.evolved?.[k]?'evolved':''}" title="${UPGRADES[k]?.name} ${v}${game.evolved?.[k]?' · 已進化':''}"><em>${icons[k]}</em><small>${game.evolved?.[k]?'進化':['','I','II','III'][v]}</small></div>`).join('');$('#dash small').textContent=game.dashCooldown>0?`${game.dashCooldown.toFixed(1)}s`:'衝刺';$('#dash').style.opacity=game.dashCooldown>0?'.55':'1';if(game.kills>lastKills)sound(320+game.kills%5*50,.04,.009);if(p.hp<lastHp)sound(140,.15,.045);lastKills=game.kills;lastHp=p.hp;}
function choose(id,level=game?.level){if(game?.state!=='upgrade'||game.level!==level)return;if(!game.chooseUpgrade(id))return;clearInput();sound(800,.15);syncState();updateHUD()}
function syncState(){if(!game)return;const state=game.state,stateKey=state==='upgrade'?`${state}:${game.level}`:state;if(stateKey===prevState)return;prevState=stateKey;if(state==='playing'){$('#overlay').hidden=true;canvas.focus();return}clearInput();const box=$('#overlay-content');$('#overlay').hidden=false;if(state==='upgrade'){box.innerHTML=`<p class="eyebrow center">A SPARK BECOMES A FLAME · LV. ${game.level}</p><h2>讓微光，更耀眼。</h2><p>選擇一項祝福。時間已暫停，慢慢決定。</p><div class="upgrade-grid">${game.choices.map((c,i)=>`<button class="upgrade-card" data-upgrade="${c.id}"><kbd>${i+1}</kbd><em>${icons[c.id]||'✦'}</em><b>${c.name} ${c.nextLevel?'· '+['','I','II','III'][c.nextLevel]:''}</b><span>${c.description}</span><small>${c.requires||'祝福'}${c.evolution?' → '+c.evolution:''}</small></button>`).join('')}</div><p>法器 III ＋ 對應祝福 II → 自動進化</p>`;const choiceLevel=game.level;box.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>choose(b.dataset.upgrade,choiceLevel));sound(650,.2)}else if(state==='paused'){box.innerHTML=`<p class="eyebrow center">THE NIGHT CAN WAIT</p><h2>喘口氣，燈還亮著。</h2><p>遊戲已暫停。<br>方向鍵 / WASD 移動 · Space 衝刺 · P / Esc 繼續</p><div class="modal-actions"><button class="primary" id="resume">繼續守夜 <span>↗</span></button><button class="secondary" id="quit">返回營地</button></div>`;$('#resume').onclick=()=>{game.togglePause();syncState()};$('#quit').onclick=home}else if(state==='dead'||state==='won'){const won=state==='won';settings.best=Math.max(settings.best,game.time);if(won)settings.wins++;save();box.innerHTML=`<p class="eyebrow center">${won?'DAWN BELONGS TO YOU':'EVERY EMBER REMEMBERS'}</p><h2>${won?'你把黎明，帶回來了。':'微光暫歇。再燃一次。'}</h2><p>${won?'長夜之王倒下了。森林重新記起光的模樣。':'每一夜都有新的祝福。換個守夜人，試試另一種組合。'}</p><div class="stats"><div><b>${timeText(game.time)}</b><span>守夜時間</span></div><div><b>${game.kills}</b><span>擊破怪物</span></div><div><b>${game.level}</b><span>最終等級</span></div></div><div class="modal-actions"><button class="primary" id="retry">再次守夜 <span>↗</span></button><button class="secondary" id="quit">選擇守夜人</button></div>`;$('#retry').onclick=start;$('#quit').onclick=home;sound(won?880:180,.5)}else{$('#overlay').hidden=true}box.querySelector('button')?.focus();}
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)&&game?.state==='playing')e.preventDefault();if(e.repeat)return;if(game?.state==='upgrade'&&/^Digit[123]$/.test(e.code)){const c=game.choices[+e.code.slice(-1)-1];if(c)choose(c.id);return}if(['Escape','KeyP'].includes(e.code)&&game){game.togglePause();clearInput();syncState();return}if(game?.state!=='playing')return;if(e.code==='Space')dash=true;keys.add(e.code)});addEventListener('keyup',e=>keys.delete(e.code));
function autoPause(){clearInput();if(game?.state==='playing'){game.togglePause();syncState()}}addEventListener('blur',autoPause);document.addEventListener('visibilitychange',()=>{if(document.hidden)autoPause()});
let pointer=null;$('#joystick').addEventListener('pointerdown',e=>{if(game?.state!=='playing'||pointer!==null)return;pointer=e.pointerId;e.currentTarget.setPointerCapture(pointer);moveStick(e)});function moveStick(e){if(e.pointerId!==pointer)return;const r=$('#joystick').getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,len=Math.hypot(x,y),s=Math.min(1,38/(len||1));axis={x:x*s/38,y:y*s/38};$('#stick').style.transform=`translate(${x*s}px,${y*s}px)`;e.preventDefault()}$('#joystick').addEventListener('pointermove',moveStick);for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#joystick').addEventListener(event,e=>{if(e.pointerId===pointer){pointer=null;axis={x:0,y:0};$('#stick').style.transform='none'}});$('#dash').addEventListener('pointerdown',e=>{if(game?.state!=='playing')return;e.preventDefault();dash=true});
function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;clock+=dt;if(game){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+axis.x,y=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+axis.y;game.step(dt,{x,y,dash});dash=false;syncState();hudClock+=dt;if(hudClock>.12){updateHUD();hudClock=0}if(game.state==='playing'&&annTime>0){annTime-=dt;if(annTime<=0)$('#announcement').style.opacity=0}}else{demo.time=settings.reduced?0:clock;demo.player.x=1200+Math.sin(clock*.05)*90;demo.player.character=selected}drawWorld(ctx,game||demo,innerWidth,innerHeight,{reducedMotion:settings.reduced,time:clock});requestAnimationFrame(frame)}requestAnimationFrame(frame);
